name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 13.10
        uses: actions/setup-node@v1
        with:
          node-version: '13.10'
      - name: Npm install
        run: |
          npm install
        env:
          CI: true
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dancastillo/dancastillo.dev/nextjs
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: Dockerfile
          tags: latest
      - name: Publish to Github Packages Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: dancastillo/dancastillo.dev/nginx
          registry: docker.pkg.github.com
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./nginx/Dockerfile
          tags: latest
      - name: Deploy package to digitalocean
        uses: appleboy/ssh-action@master
        env:
          GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          envs: GITHUB_USERNAME, GITHUB_TOKEN
          script: |
            docker stop $(docker ps -a -q)
            docker container rm /nextjs-container
            docker container rm /nginx-container
            docker login -u $GITHUB_USERNAME -p $GITHUB_TOKEN docker.pkg.github.com
            docker pull docker.pkg.github.com/dancastillo/dancastillo.dev/nextjs:latest
            docker pull docker.pkg.github.com/dancastillo/dancastillo.dev/nginx:latest
            docker run --network my-network -d --name nextjs-container docker.pkg.github.com/dancastillo/dancastillo.dev/nextjs:latest
            docker run --network my-network -d --name nginx-container --link nextjs-container:nextjs -p 443:443 docker.pkg.github.com/dancastillo/dancastillo.dev/nginx:latest
            docker cp /etc/nginx/snippets/* $(docker ps -aqf "name=nginx-container"):/etc/nginx/snippets/*
            docker cp /etc/nginx/certs/dancastillo_dev_chain.crt $(docker ps -aqf "name=nginx-container"):/etc/nginx/certs/dancastillo_dev_chain.crt
